-- ==============================================================================
-- 1. CREACIÓN DE TIPOS ENUMERADOS (ENUMS)
-- ==============================================================================
CREATE TYPE ENUM_DIFFICULTY AS ENUM ('EASY', 'MEDIUM', 'HARD', 'EPIC');
CREATE TYPE ENUM_FREQUENCY AS ENUM ('DAILY', 'WEEKLY');
CREATE TYPE ENUM_PERIOD_UNIT AS ENUM ('DAYS', 'WEEKS', 'MONTHS');
CREATE TYPE ENUM_COMPLETION_CRITERIA AS ENUM ('TIMER', 'REPETITIONS', 'EVIDENCE');
CREATE TYPE ENUM_EVIDENCE AS ENUM ('PHOTO', 'VIDEO', 'HEALTH_CONNECT');
CREATE TYPE ENUM_MEASUREMENT_UNIT AS ENUM ('REPS', 'SERIES', 'KMS', 'CALS');

-- ==============================================================================
-- 2. NÚCLEO DE IDENTIDAD Y USUARIO
-- ==============================================================================

CREATE TABLE LULM_PERSON (
    ID_PERSON SERIAL PRIMARY KEY,
    DSC_PERSON_NAME VARCHAR(50) NOT NULL,
    DSC_PERSON_LAST_NAME VARCHAR(50) NOT NULL,
    DSC_PERSON_PHONE_NUMBER VARCHAR(20),
    DSC_PERSON_EMAIL VARCHAR(150) UNIQUE NOT NULL,
    FEC_PERSON_BIRTHDATE DATE,
    STATUS_PERSON_IS_ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE LULM_USER_PLAYER_CLASS (
    ID_USER_PLAYER_CLASS SERIAL PRIMARY KEY,
    DSC_USER_PLAYER_CLASS_NAME VARCHAR(50) NOT NULL,
    DSC_USER_PLAYER_CLASS_DESCRIPTION TEXT,
    NUM_CLASS_XP_MULT_STUDY NUMERIC(5,2) DEFAULT 1.00,
    NUM_CLASS_XP_MULT_SPORT NUMERIC(5,2) DEFAULT 1.00,
    NUM_CLASS_XP_MULT_FOOD NUMERIC(5,2) DEFAULT 1.00,
    STATUS_USER_PLAYER_CLASS_IS_ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE LULM_PLAYER_USER (
    ID_PLAYER_USER SERIAL PRIMARY KEY,
    ID_PERSON INTEGER UNIQUE NOT NULL REFERENCES LULM_PERSON(ID_PERSON) ON DELETE CASCADE,
    ID_USER_PLAYER_CLASS INTEGER NOT NULL REFERENCES LULM_USER_PLAYER_CLASS(ID_USER_PLAYER_CLASS),
    DSC_PLAYER_USER_USERNAME VARCHAR(50) UNIQUE NOT NULL,
    DSC_PLAYER_USER_PASSWORD VARCHAR(255) NOT NULL,
    NUM_PLAYER_USER_LEVEL INTEGER DEFAULT 1,
    NUM_PLAYER_USER_EXPERIENCE_POINTS INTEGER DEFAULT 0,
    NUM_PLAYER_USER_DAYS_STREAK INTEGER DEFAULT 0,
    FEC_PLAYER_USER_LAST_LOGIN TIMESTAMP,
    FEC_PLAYER_USER_CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS_PLAYER_USER_IS_ACTIVE BOOLEAN DEFAULT TRUE
);

-- ==============================================================================
-- 3. ESTRUCTURA DE HÁBITOS Y DISCIPLINAS
-- ==============================================================================

CREATE TABLE LULM_HABIT_CATEGORY (
    ID_HABIT_CATEGORY SERIAL PRIMARY KEY,
    DSC_HABIT_CATEGORY_NAME VARCHAR(50) NOT NULL,
    DSC_HABIT_CATEGORY_DESCRIPTION TEXT,
    STATUS_HABIT_CATEGORY_IS_ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE LULM_HABIT_DISCIPLINE (
    ID_HABIT_DISCIPLINE SERIAL PRIMARY KEY,
    ID_HABIT_CATEGORY INTEGER NOT NULL REFERENCES LULM_HABIT_CATEGORY(ID_HABIT_CATEGORY),
    DSC_HABIT_DISCIPLINE_NAME VARCHAR(50) NOT NULL,
    DSC_HABIT_DISCIPLINE_DESCRIPTION TEXT,
    STATUS_HABIT_DISCIPLINE_IS_ACTIVE BOOLEAN DEFAULT TRUE
);


CREATE TABLE LULM_HABIT (
    ID_HABIT SERIAL PRIMARY KEY,
    ID_HABIT_DISCIPLINE INTEGER NOT NULL REFERENCES LULM_HABIT_DISCIPLINE(ID_HABIT_DISCIPLINE),
    ID_PLAYER_USER INTEGER NOT NULL REFERENCES LULM_PLAYER_USER(ID_PLAYER_USER) ON DELETE CASCADE,
    DSC_HABIT_TITLE VARCHAR(100) NOT NULL,
    DSC_HABIT_DESCRIPTION TEXT,
    STATUS_HABIT_IS_ACTIVE BOOLEAN DEFAULT TRUE
);

-- ==============================================================================
-- 4. GESTIÓN DE TAREAS Y CRITERIOS DE ÉXITO
-- ==============================================================================

CREATE TABLE LULM_HABIT_TASK (
    ID_HABIT_TASK SERIAL PRIMARY KEY,
    ID_HABIT INTEGER NOT NULL REFERENCES LULM_HABIT(ID_HABIT) ON DELETE CASCADE,
    ID_HABIT_DISCIPLINE INTEGER REFERENCES LULM_HABIT_DISCIPLINE(ID_HABIT_DISCIPLINE),
    DSC_HABIT_TASK_TITLE VARCHAR(100) NOT NULL,
    DSC_HABIT_TASK_DESCRIPTION TEXT,
    DSC_HABIT_TASK_WEEK_DAYS VARCHAR(60),
    TYPE_HABIT_TASK_DIFFICULTY ENUM_DIFFICULTY NOT NULL,
    NUM_HABIT_TASK_XP_VALUE INTEGER DEFAULT 0,
    TYPE_HABIT_TASK_FREQUENCY ENUM_FREQUENCY NOT NULL,
    NUM_HABIT_TASK_PERIOD_LENGTH INTEGER NOT NULL,
    TYPE_HABIT_TASK_PERIOD_UNIT ENUM_PERIOD_UNIT NOT NULL,
    FEC_HABIT_TASK_START_DATE DATE NOT NULL,
    STATUS_HABIT_TASK_IS_COMPLETED BOOLEAN DEFAULT FALSE,
    TYPE_COMPLETION_CRITERIA ENUM_COMPLETION_CRITERIA NOT NULL,
    TYPE_HABIT_TASK_EVIDENCE ENUM_EVIDENCE,
    STATUS_HABIT_TASK_IS_ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE LULT_HABIT_TASK_TIMER_CRITERIA (
    ID_HABIT_TASK_TIMER_CRITERIA SERIAL PRIMARY KEY,
    ID_HABIT_TASK INTEGER UNIQUE NOT NULL REFERENCES LULM_HABIT_TASK(ID_HABIT_TASK) ON DELETE CASCADE,
    NUM_SECONDS_DEFINED INTEGER NOT NULL,
    NUM_SECONDS_LONG INTEGER DEFAULT 0,
    TYPE_PAUSE_IS_ALLOWED BOOLEAN DEFAULT FALSE,
    STATUS_TIMER_CRITERIA_IS_ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE LULT_HABIT_TASK_REPETITIONS_CRITERIA (
    ID_HABIT_TASK_REPETITIONS_CRITERIA SERIAL PRIMARY KEY,
    ID_HABIT_TASK INTEGER UNIQUE NOT NULL REFERENCES LULM_HABIT_TASK(ID_HABIT_TASK) ON DELETE CASCADE,
    NUM_REPETITIONS_OBJECTIVE INTEGER NOT NULL,
    TYPE_UNITY_MEASUREMENT_UNIT ENUM_MEASUREMENT_UNIT NOT NULL,
    STATUS_IS_PARTIAL_ALLOWED BOOLEAN DEFAULT FALSE,
    STATUS_REPETITIONS_CRITERIA_IS_ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE LULT_HABIT_TASK_EVIDENCE_STORAGE (
    ID_EVIDENCE SERIAL PRIMARY KEY,
    ID_HABIT_TASK INTEGER NOT NULL REFERENCES LULM_HABIT_TASK(ID_HABIT_TASK) ON DELETE CASCADE,
    DSC_EVIDENCE_PATH_URL TEXT,
    DSC_HEALTH_DATA_JSON TEXT,
    FEC_UPLOADED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ==============================================================================
-- 5. ECONOMÍA, RECOMPENSAS Y RACHAS
-- ==============================================================================

CREATE TABLE LULM_REWARD_ITEM_TYPE (
    ID_REWARD_ITEM_TYPE SERIAL PRIMARY KEY,
    DSC_REWARD_ITEM_TYPE_NAME VARCHAR(50) NOT NULL,
    DSC_REWARD_ITEM_TYPE_DESC TEXT,
    STATUS_REWARD_ITEM_TYPE_IS_ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE LULM_REWARD_ITEM (
    ID_REWARD_ITEM SERIAL PRIMARY KEY,
    ID_REWARD_ITEM_TYPE INTEGER NOT NULL REFERENCES LULM_REWARD_ITEM_TYPE(ID_REWARD_ITEM_TYPE),
    DSC_REWARD_ITEM_NAME VARCHAR(100) NOT NULL,
    DSC_REWARD_ITEM_DESCRIPTION TEXT,
    NUM_REWARD_ITEM_COST_GOLD INTEGER NOT NULL,
    NUM_REWARD_ITEM_EFFECT_VALUE NUMERIC(10,2),
    STATUS_REWARD_ITEM_IS_ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE LULT_PLAYER_INVENTORY (
    ID_INVENTORY SERIAL PRIMARY KEY,
    ID_PLAYER_USER INTEGER NOT NULL REFERENCES LULM_PLAYER_USER(ID_PLAYER_USER) ON DELETE CASCADE,
    ID_REWARD_ITEM INTEGER NOT NULL REFERENCES LULM_REWARD_ITEM(ID_REWARD_ITEM),
    NUM_INVENTORY_QUANTITY INTEGER DEFAULT 1,
    STATUS_INVENTORY_IS_EQUIPPED BOOLEAN DEFAULT FALSE,
    FEC_ACQUIRED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE LULH_STREAK_LOG (
    ID_STREAK_LOG SERIAL PRIMARY KEY,
    ID_PLAYER_USER INTEGER NOT NULL REFERENCES LULM_PLAYER_USER(ID_PLAYER_USER) ON DELETE CASCADE,
    NUM_STREAK_COUNT INTEGER NOT NULL,
    FEC_LOG_DATE DATE NOT NULL,
    TYPE_PROTECTION_USED BOOLEAN DEFAULT FALSE
);

-- ==============================================================================
-- 6. CREACIÓN DE ÍNDICES (OPTIMIZACIÓN DE BÚSQUEDAS Y JOINS)
-- ==============================================================================

-- Índices para Logins y Búsquedas Rápidas (El "Select" más frecuente)
CREATE INDEX IDX_PERSON_EMAIL ON LULM_PERSON(DSC_PERSON_EMAIL);
CREATE INDEX IDX_PLAYER_USERNAME ON LULM_PLAYER_USER(DSC_PLAYER_USER_USERNAME);

-- Índices de Llaves Foráneas (Cruciales para hacer JOINs rápidos)
CREATE INDEX IDX_PLAYER_CLASS ON LULM_PLAYER_USER(ID_USER_PLAYER_CLASS);

-- Índices para el Dashboard Principal (Cargar los hábitos y tareas de un usuario)
CREATE INDEX IDX_HABIT_PLAYER ON LULM_HABIT(ID_PLAYER_USER);
CREATE INDEX IDX_TASK_HABIT ON LULM_HABIT_TASK(ID_HABIT);

-- Índices para Inventario y Rachas (Consultas pesadas de historial)
CREATE INDEX IDX_INVENTORY_PLAYER ON LULT_PLAYER_INVENTORY(ID_PLAYER_USER);
CREATE INDEX IDX_STREAK_PLAYER_DATE ON LULH_STREAK_LOG(ID_PLAYER_USER, FEC_LOG_DATE);

-- Índices parciales (Avanzado): Solo indexa las tareas activas/incompletas 
-- Esto hace que la carga del "To-Do List" diario del jugador vuele.
CREATE INDEX IDX_ACTIVE_INCOMPLETE_TASKS 
ON LULM_HABIT_TASK(ID_HABIT_TASK) 
WHERE STATUS_HABIT_TASK_IS_COMPLETED = FALSE AND STATUS_HABIT_TASK_IS_ACTIVE = TRUE;
