using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LevelUpLife_Backend.Migrations
{
    /// <inheritdoc />
    public partial class Issue29StreakCompletionTracking : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Table was missing from previous migrations (was only in SQL backup).
            // Create it here if it doesn't exist, then add the new column.
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "LULH_STREAK_LOG" (
                    "ID_STREAK_LOG" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "FEC_LOG_DATE" DATE NOT NULL,
                    "ID_PLAYER_USER" INTEGER NOT NULL REFERENCES "LULM_PLAYER_USER"("ID_PLAYER_USER") ON DELETE CASCADE,
                    "NUM_STREAK_COUNT" INTEGER NOT NULL,
                    "TYPE_PROTECTION_USED" BOOLEAN NOT NULL DEFAULT FALSE
                );

                CREATE INDEX IF NOT EXISTS "IX_LULH_STREAK_LOG_ID_PLAYER_USER"
                    ON "LULH_STREAK_LOG"("ID_PLAYER_USER");

                ALTER TABLE "LULH_STREAK_LOG"
                    ADD COLUMN IF NOT EXISTS "STATUS_STREAK_COMPLETION_RECORDED" BOOLEAN NOT NULL DEFAULT TRUE;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE "LULH_STREAK_LOG"
                    DROP COLUMN IF EXISTS "STATUS_STREAK_COMPLETION_RECORDED";
                """);
        }
    }
}
