// <auto-generated />
using System;
using LevelUpLifeBackend.Data;
using LevelUpLifeBackend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LevelUpLife_Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("202606130003_BlockBStreakProtection")]
    partial class BlockBStreakProtection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ENUM_COMPLETION_CRITERIA", new[] { "EVIDENCE", "REPETITIONS", "TIMER" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ENUM_COMPLETION_CRITERIA", "TaskCompletionCriteria", new[] { "REPETITIONS", "TIMER", "EVIDENCE" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ENUM_DIFFICULTY", new[] { "EASY", "EPIC", "HARD", "MEDIUM" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ENUM_DIFFICULTY", "TaskDifficulty", new[] { "EASY", "MEDIUM", "HARD", "EPIC" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ENUM_EVIDENCE", new[] { "HEALTH_CONNECT", "PHOTO", "VIDEO" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ENUM_EVIDENCE", "TaskEvidence", new[] { "PHOTO", "VIDEO", "HEALTH_CONNECT" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ENUM_FREQUENCY", new[] { "DAILY", "WEEKLY" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ENUM_FREQUENCY", "TaskFrequency", new[] { "DAILY", "WEEKLY" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ENUM_MEASUREMENT_UNIT", new[] { "CALS", "KMS", "REPS", "SERIES" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ENUM_MEASUREMENT_UNIT", "MeasurementUnit", new[] { "REPS", "SERIES", "KMS", "CALS" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ENUM_PERIOD_UNIT", new[] { "DAYS", "MONTHS", "WEEKS" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ENUM_PERIOD_UNIT", "TaskPeriodUnit", new[] { "DAYS", "WEEKS", "MONTHS" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LevelUpLifeBackend.Models.EvidenceStorage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_EVIDENCE");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EvidencePathUrl")
                        .HasColumnType("text")
                        .HasColumnName("DSC_EVIDENCE_PATH_URL");

                    b.Property<int>("HabitTaskId")
                        .HasColumnType("integer")
                        .HasColumnName("ID_HABIT_TASK");

                    b.Property<string>("HealthDataJson")
                        .HasColumnType("text")
                        .HasColumnName("DSC_HEALTH_DATA_JSON");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FEC_UPLOADED");

                    b.HasKey("Id");

                    b.HasIndex("HabitTaskId");

                    b.ToTable("LULT_HABIT_TASK_EVIDENCE_STORAGE", (string)null);
                });

            modelBuilder.Entity("LevelUpLifeBackend.Models.Habit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_HABIT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DSC_HABIT_DESCRIPTION");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer")
                        .HasColumnName("ID_HABIT_DISCIPLINE");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("STATUS_HABIT_IS_ACTIVE");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("DSC_HABIT_TITLE");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("ID_PLAYER_USER");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("UserId");

                    b.ToTable("LULM_HABIT", (string)null);
                });

            modelBuilder.Entity("LevelUpLifeBackend.Models.HabitCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_HABIT_CATEGORY");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DSC_HABIT_CATEGORY_DESCRIPTION");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("STATUS_HABIT_CATEGORY_IS_ACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("DSC_HABIT_CATEGORY_NAME");

                    b.HasKey("Id");

                    b.ToTable("LULM_HABIT_CATEGORY", (string)null);
                });

            modelBuilder.Entity("LevelUpLifeBackend.Models.HabitDiscipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_HABIT_DISCIPLINE");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("ID_HABIT_CATEGORY");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DSC_HABIT_DISCIPLINE_DESCRIPTION");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("STATUS_HABIT_DISCIPLINE_IS_ACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("DSC_HABIT_DISCIPLINE_NAME");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("LULM_HABIT_DISCIPLINE", (string)null);
                });

            modelBuilder.Entity("LevelUpLifeBackend.Models.HabitTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_HABIT_TASK");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TaskCompletionCriteria>("CompletionCriteria")
                        .HasColumnType("\"ENUM_COMPLETION_CRITERIA\"")
                        .HasColumnName("TYPE_COMPLETION_CRITERIA");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("DSC_HABIT_TASK_DESCRIPTION");

                    b.Property<TaskDifficulty>("Difficulty")
                        .HasColumnType("\"ENUM_DIFFICULTY\"")
                        .HasColumnName("TYPE_HABIT_TASK_DIFFICULTY");

                    b.Property<TaskEvidence?>("Evidence")
                        .HasColumnType("\"ENUM_EVIDENCE\"")
                        .HasColumnName("TYPE_HABIT_TASK_EVIDENCE");

                    b.Property<TaskFrequency>("Frequency")
                        .HasColumnType("\"ENUM_FREQUENCY\"")
                        .HasColumnName("TYPE_HABIT_TASK_FREQUENCY");

                    b.Property<int>("HabitId")
                        .HasColumnType("integer")
                        .HasColumnName("ID_HABIT");

                    b.Property<int>("PeriodLength")
                        .HasColumnType("integer")
                        .HasColumnName("NUM_HABIT_TASK_PERIOD_LENGTH");

                    b.Property<TaskPeriodUnit>("PeriodUnit")
                        .HasColumnType("\"ENUM_PERIOD_UNIT\"")
                        .HasColumnName("TYPE_HABIT_TASK_PERIOD_UNIT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("FEC_HABIT_TASK_START_DATE");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("DSC_HABIT_TASK_TITLE");

                    b.Property<string>("WeekDays")
                        .HasColumnType("text")
                        .HasColumnName("DSC_HABIT_TASK_WEEK_DAYS");

                    b.HasKey("Id");

                    b.HasIndex("HabitId");

                    b.ToTable("LULM_HABIT_TASK", (string)null);
                });

            modelBuilder.Entity("LevelUpLifeBackend.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_PERSON");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("FEC_PERSON_BIRTHDATE");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("DSC_PERSON_EMAIL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("STATUS_PERSON_IS_ACTIVE");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("DSC_PERSON_LAST_NAME");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("DSC_PERSON_NAME");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("DSC_PERSON_PHONE_NUMBER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("LULM_PERSON", (string)null);
                });

            modelBuilder.Entity("LevelUpLifeBackend.Models.PlayerUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_PLAYER_USER");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("integer")
                        .HasColumnName("ID_USER_PLAYER_CLASS");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FEC_PLAYER_USER_CREATION_DATE");

                    b.Property<int>("DaysStreak")
                        .HasColumnType("integer")
                        .HasColumnName("NUM_PLAYER_USER_DAYS_STREAK");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("integer")
                        .HasColumnName("NUM_PLAYER_USER_EXPERIENCE_POINTS");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("STATUS_PLAYER_USER_IS_ACTIVE");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FEC_PLAYER_USER_LAST_LOGIN");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("NUM_PLAYER_USER_LEVEL");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("DSC_PLAYER_USER_PASSWORD");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("ID_PERSON");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("DSC_PLAYER_USER_USERNAME");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("LULM_PLAYER_USER", (string)null);
                });

            modelBuilder.Entity("LevelUpLifeBackend.Models.RepetitionCriteria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_HABIT_TASK_REPETITIONS_CRITERIA");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HabitTaskId")
                        .HasColumnType("integer")
                        .HasColumnName("ID_HABIT_TASK");

                    b.Property<int>("NumRepetitionsObjective")
                        .HasColumnType("integer")
                        .HasColumnName("NUM_REPETITIONS_OBJECTIVE");

                    b.Property<bool>("StatusIsPartialAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("STATUS_IS_PARTIAL_ALLOWED");

                    b.Property<bool>("StatusRepetitionsCriteriaIsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("STATUS_REPETITIONS_CRITERIA_IS_ACTIVE");

                    b.Property<MeasurementUnit>("TypeUnityMeasurementUnit")
                        .HasColumnType("\"ENUM_MEASUREMENT_UNIT\"")
                        .HasColumnName("TYPE_UNITY_MEASUREMENT_UNIT");

                    b.HasKey("Id");

                    b.HasIndex("HabitTaskId")
                        .IsUnique();

                    b.ToTable("LULT_HABIT_TASK_REPETITIONS_CRITERIA", (string)null);
                });

            modelBuilder.Entity("LevelUpLifeBackend.Models.UserPlayerClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_USER_PLAYER_CLASS");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DSC_USER_PLAYER_CLASS_DESCRIPTION");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("STATUS_USER_PLAYER_CLASS_IS_ACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("DSC_USER_PLAYER_CLASS_NAME");

                    b.Property<double>("XpMultFood")
                        .HasColumnType("double precision")
                        .HasColumnName("NUM_CLASS_XP_MULT_FOOD");

                    b.Property<double>("XpMultSport")
                        .HasColumnType("double precision")
                        .HasColumnName("NUM_CLASS_XP_MULT_SPORT");

                    b.Property<double>("XpMultStudy")
                        .HasColumnType("double precision")
                        .HasColumnName("NUM_CLASS_XP_MULT_STUDY");

                    b.HasKey("Id");

                    b.ToTable("LULM_USER_PLAYER_CLASS", (string)null);
                });

            modelBuilder.Entity("LevelUpLifeBackend.Models.EvidenceStorage", b =>
                {
                    b.HasOne("LevelUpLifeBackend.Models.HabitTask", "HabitTask")
                        .WithMany()
                        .HasForeignKey("HabitTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HabitTask");
                });

            modelBuilder.Entity("LevelUpLifeBackend.Models.Habit", b =>
                {
                    b.HasOne("LevelUpLifeBackend.Models.HabitDiscipline", "Discipline")
                        .WithMany()
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LevelUpLifeBackend.Models.PlayerUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LevelUpLifeBackend.Models.HabitDiscipline", b =>
                {
                    b.HasOne("LevelUpLifeBackend.Models.HabitCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LevelUpLifeBackend.Models.HabitTask", b =>
                {
                    b.HasOne("LevelUpLifeBackend.Models.Habit", "Habit")
                        .WithMany()
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habit");
                });

            modelBuilder.Entity("LevelUpLifeBackend.Models.PlayerUser", b =>
                {
                    b.HasOne("LevelUpLifeBackend.Models.UserPlayerClass", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LevelUpLifeBackend.Models.Person", "Person")
                        .WithOne()
                        .HasForeignKey("LevelUpLifeBackend.Models.PlayerUser", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("LevelUpLifeBackend.Models.RepetitionCriteria", b =>
                {
                    b.HasOne("LevelUpLifeBackend.Models.HabitTask", "HabitTask")
                        .WithOne("RepetitionCriteria")
                        .HasForeignKey("LevelUpLifeBackend.Models.RepetitionCriteria", "HabitTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HabitTask");
                });

            modelBuilder.Entity("LevelUpLifeBackend.Models.HabitTask", b =>
                {
                    b.Navigation("RepetitionCriteria");
                });
#pragma warning restore 612, 618
        }
    }
}
