// <auto-generated />
using System;
using LevelUpLifeBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LevelUpLife_Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260502174226_12-update-habit")]
    partial class _12updatehabit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LevelUpLifeBackend.Models.Habit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_HABIT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DSC_HABIT_DESCRIPTION");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer")
                        .HasColumnName("ID_HABIT_DISCIPLINE");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("STATUS_HABIT_IS_ACTIVE");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("DSC_HABIT_TITLE");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("ID_PLAYER_USER");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("UserId");

                    b.ToTable("LULM_HABIT", (string)null);
                });

            modelBuilder.Entity("LevelUpLifeBackend.Models.HabitCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_HABIT_CATEGORY");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DSC_HABIT_CATEGORY_DESCRIPTION");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("STATUS_HABIT_CATEGORY_IS_ACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("DSC_HABIT_CATEGORY_NAME");

                    b.HasKey("Id");

                    b.ToTable("LULM_HABIT_CATEGORY", (string)null);
                });

            modelBuilder.Entity("LevelUpLifeBackend.Models.HabitDiscipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_HABIT_DISCIPLINE");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("ID_HABIT_CATEGORY");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DSC_HABIT_DISCIPLINE_DESCRIPTION");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("STATUS_HABIT_DISCIPLINE_IS_ACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("DSC_HABIT_DISCIPLINE_NAME");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("LULM_HABIT_DISCIPLINE", (string)null);
                });

            modelBuilder.Entity("LevelUpLifeBackend.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_PERSON");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("FEC_PERSON_BIRTHDATE");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("DSC_PERSON_EMAIL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("STATUS_PERSON_IS_ACTIVE");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("DSC_PERSON_LAST_NAME");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("DSC_PERSON_NAME");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("DSC_PERSON_PHONE_NUMBER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("LULM_PERSON", (string)null);
                });

            modelBuilder.Entity("LevelUpLifeBackend.Models.PlayerUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_PLAYER_USER");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("integer")
                        .HasColumnName("ID_USER_PLAYER_CLASS");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FEC_PLAYER_USER_CREATION_DATE");

                    b.Property<int>("DaysStreak")
                        .HasColumnType("integer")
                        .HasColumnName("NUM_PLAYER_USER_DAYS_STREAK");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("integer")
                        .HasColumnName("NUM_PLAYER_USER_EXPERIENCE_POINTS");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("STATUS_PLAYER_USER_IS_ACTIVE");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FEC_PLAYER_USER_LAST_LOGIN");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("NUM_PLAYER_USER_LEVEL");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("DSC_PLAYER_USER_PASSWORD");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("ID_PERSON");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("DSC_PLAYER_USER_USERNAME");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("LULM_PLAYER_USER", (string)null);
                });

            modelBuilder.Entity("LevelUpLifeBackend.Models.UserPlayerClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_USER_PLAYER_CLASS");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DSC_USER_PLAYER_CLASS_DESCRIPTION");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("STATUS_USER_PLAYER_CLASS_IS_ACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("DSC_USER_PLAYER_CLASS_NAME");

                    b.Property<double>("XpMultFood")
                        .HasColumnType("double precision")
                        .HasColumnName("NUM_CLASS_XP_MULT_FOOD");

                    b.Property<double>("XpMultSport")
                        .HasColumnType("double precision")
                        .HasColumnName("NUM_CLASS_XP_MULT_SPORT");

                    b.Property<double>("XpMultStudy")
                        .HasColumnType("double precision")
                        .HasColumnName("NUM_CLASS_XP_MULT_STUDY");

                    b.HasKey("Id");

                    b.ToTable("LULM_USER_PLAYER_CLASS", (string)null);
                });

            modelBuilder.Entity("LevelUpLifeBackend.Models.Habit", b =>
                {
                    b.HasOne("LevelUpLifeBackend.Models.HabitDiscipline", "Discipline")
                        .WithMany()
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LevelUpLifeBackend.Models.PlayerUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LevelUpLifeBackend.Models.HabitDiscipline", b =>
                {
                    b.HasOne("LevelUpLifeBackend.Models.HabitCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LevelUpLifeBackend.Models.PlayerUser", b =>
                {
                    b.HasOne("LevelUpLifeBackend.Models.UserPlayerClass", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LevelUpLifeBackend.Models.Person", "Person")
                        .WithOne()
                        .HasForeignKey("LevelUpLifeBackend.Models.PlayerUser", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Person");
                });
#pragma warning restore 612, 618
        }
    }
}
